name: Pharma Job Checker (24/7)

on:
  # This allows you to run the workflow manually from the Actions tab
  workflow_dispatch:

  # This runs the workflow automatically on a schedule
  schedule:
    # Runs once every hour, on the hour. Operates 24/7.
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run the scraper script
        env:
          # These secrets are loaded from your repository settings
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python pharma_checker.py
